name: pull-request
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'pre-commit'
        uses: dycw/action-pre-commit@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repos: |-
            dycw/pre-commit-hook-nitpick
            pre-commit/pre-commit-hooks
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'ruff'
        uses: dycw/action-ruff@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
